on:
  issues:
    types: [labeled]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - uses: crazy-max/ghaction-dump-context@v1
      - name: Checkout
        uses: actions/checkout@master
      - name: Hello world action step
        uses: ./src/ # Uses an action in the root directory
        id: hello
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          project: "https://github.com/orgs/github/projects/1"
          column: "On Deck"
