on:
  issues:
    types: [labeled]
jobs:
  Move_Labeled_Issue_On_Project_Board:
    runs-on: ubuntu-latest
    steps:
    - uses: action/Card-automation@master
      with:
        action-token: "${{ secrets.GITHUB_TOKEN }}"
        project: "https://github.com/orgs/github/projects/1"
        column: "On Deck"
